# Prometheus configuration for ZodiaCore staging environment
# Configures scraping targets for all microservices and monitoring endpoints
# Follows observability best practices for metrics collection

global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds

# Rule files - can be used for alerting rules
rule_files:
  # - "alert_rules.yml"

# Scrape configurations for all ZodiaCore services
scrape_configs:
  # Backend API Gateway - collects HTTP metrics
  - job_name: 'zodia-core-backend'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Vedic Astrology Service
  - job_name: 'zodia-core-vedic-service'
    static_configs:
      - targets: ['vedic-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Western Astrology Service
  - job_name: 'zodia-core-western-service'
    static_configs:
      - targets: ['western-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Mundane Astrology Service
  - job_name: 'zodia-core-mundane-service'
    static_configs:
      - targets: ['mundane-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Health check endpoints for all services
  - job_name: 'zodia-core-health-checks'
    static_configs:
      - targets:
          [
            'api-gateway:3000',
            'vedic-service:3001',
            'western-service:3002',
            'mundane-service:3003',
          ]
    metrics_path: '/health'
    scrape_interval: 30s # Health checks less frequent
    scrape_timeout: 10s
    # Custom labels for health checks
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        regex: '([^-]+)-service:(\d+)'
        replacement: '${1}'

  # Node Exporter for system metrics (if running on host)
  # Uncomment if you want to monitor the host system
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['localhost:9100']

  # Prometheus itself for self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
# Remote write configuration (for production setups)
# remote_write:
#   - url: "https://prometheus-prod.example.com/api/v1/write"

# Remote read configuration (for production setups)
# remote_read:
#   - url: "https://prometheus-prod.example.com/api/v1/read"
